# This is a basic workflow to help you get started with Actions

name: MELODY

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Sync
        run: git pull melody0 ${{ secrets.MELODYDATA }} --allow-unrelated-histories --depth=1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo apt install ffmpeg
          sudo npm install -g n
          sudo n latest
          node -v
          npm install ytdl-core
          npm install yt-search
          npm install discord.js
          npm install @discordjs/voice libsodium-wrappers
          npm install @discordjs/opus

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env: 
          DISCORD_TOKEN: ${{ secrets.MELODY_0_TOKEN }}
        run: node index.js
